Synolia\SyliusSchedulerCommandPlugin\Entity\Command:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
        command:
            - NotBlank: ~
        cronExpression:
            - NotBlank: ~
            - Length:
                min: 9
        priority:
            - NotBlank: ~
            - PositiveOrZero: ~
        logFilePrefix:
            - Callback: [ Synolia\SyliusSchedulerCommandPlugin\Validator\LogfilePrefixPropertyValidator, validate ]

Synolia\SyliusSchedulerCommandPlugin\Entity\ScheduledCommand:
    properties:
        name:
            - NotNull: ~
            - NotBlank: ~
            - Length:
                min: 2
        command:
            - NotBlank: ~
        logFile:
            - Callback: [ Synolia\SyliusSchedulerCommandPlugin\Validator\LogfilePropertyValidator, validate ]

